name: Performance Tests
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Debug

jobs:
  performance_test:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Install compiler
        run: sudo apt update && sudo apt-get install -y clang-14

      - name: Configure CMake
        env:
          CC: "/usr/lib/llvm-14/bin/clang"
          CXX: "/usr/lib/llvm-14/bin/clang++"
          CXX_STANDARD: 20
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        id: build_step
        shell: bash
        run: |
          # interesting summary data on stderr
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -t compilation_benchmark 2>&1 | tee ${{github.workspace}}/build/compilation_output.log
          FRONT_END_TIME=$(grep "Clang front-end timer" ${{github.workspace}}/build/compilation_output.log | awk '{print $1}')

          # generate summary with expandable section
          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "  <summary>Clang front-end: ${FRONT_END_TIME} seconds</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`" >> $GITHUB_STEP_SUMMARY
          cat ${{github.workspace}}/build/compilation_output.log >> $GITHUB_STEP_SUMMARY
          echo "  \`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

      - name: 'Upload Compilation Trace'
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: compilation_trace.json
          path: ${{github.workspace}}/build/benchmark/CMakeFiles/compilation_benchmark.dir/big_nexus.cpp.json

