name: Single Header
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  push:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_GENERATOR: Ninja

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_single_header:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Install build tools
        run: |
          sudo apt install -y ninja-build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build -t release_header

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: cib.hpp
          path: ${{github.workspace}}/build/include/cib/cib.hpp
