name: Single Header
permissions: read-all

on:
  workflow_dispatch:
  merge_group:
  push:
    branches: [ main ]

env:
  DEBIAN_FRONTEND: noninteractive
  CMAKE_GENERATOR: Ninja

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_single_header:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Install build tools
        run: |
          sudo apt install -y ninja-build

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build -t release_header

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: cib.hpp
          path: ${{github.workspace}}/build/include/cib/cib.hpp
